[Iteration 1]Merge spring 24 main to snp-cloud main
snap-cloud/snapcon pull request #356
Opened 2024-03-08 19:13 UTC by warrenlet

**Checklist**

- [x] I have read the [Contribution & Best practices Guide](https://github.com/openSUSE/osem/blob/master/CONTRIBUTING.md).
- [x] My branch is up-to-date with the upstream `master` branch.
- [x] The tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works(if appropriate).
- [x] I have added necessary documentation (if appropriate).

**Short description of what this resolves/which [issues](https://github.com/openSUSE/osem/issues) does this fix?:**

https://github.com/snap-cloud/snapcon/pull/344

**Changes proposed in this pull request:**

- changes attribute 'submission instructions' to 'submission template' for event_types model. Changed corresponding view, controller, model, and testing code.
- Makes it such that no user (admins, non-admins) can see these toggles. An admin is still able to change these settings by going to administration->users->edit. The button for admin has also been updated from a checkbox to a toggle switch.
- Update the  INSTALL_SNAPCON.md to provide instruction to the situation of fork safty issues from MacOS

2024-03-08 19:35 UTC, fp456 commented on app/mailers/mailbot.rb
> +      @ticket_purchase.ticket.email_body = @ticket_purchase.generate_confirmation_mail(@ticket_purchase.ticket.email_body)
The conditional statements are very self explanatory so I think this comment can be deleted

2024-03-08 19:39 UTC, cycomachead commented on app/views/mailbot/custom_ticket_confirmation_template.html.erb
> +<%= render partial: "layouts/mailbot_footer" %>
Should have a newline.

```suggestion
<%= render partial: "layouts/mailbot_footer" %>

```

2024-03-08 20:31 UTC, fp456 requested changes
Hi! Good overall, just some clean up to do and data to be updated about the members of the team

2024-03-11 18:14 UTC, fp456 commented on app/services/email_template_parser.rb
> +  # rubocop:enable Metrics/AbcSize, Metrics/ParameterLists
You can remove this line

2024-03-11 18:17 UTC, fp456 commented on config/routes.rb
> +# rubocop:disable Metrics/BlockLength
If this is a comment, and the line won't be used, you can delete

2024-03-11 18:20 UTC, fp456 commented on db/migrate/20230418211400_create_currency_conversions.rb
> +
you can remove this empty line

2024-03-11 18:23 UTC, fp456 commented on spec/features/currency_conversions_spec.rb
> +
you can remove this empty line

2024-03-11 18:23 UTC, fp456 commented on spec/features/currency_conversions_spec.rb
> +
you can remove this empty line

2024-03-11 18:28 UTC, fp456 requested changes
just some empty lines, tiny stuff but again overall looks good :)

2024-03-12 04:58 UTC, cycomachead approved these changes
Really minor things, but I will merge and might make a tidy-ing PR myself then deploy soon.

2024-03-12 05:25 UTC, merged